kind: pipeline
name: tests

steps:
- name: compile
  image: alpine:latest
  commands:
    - apk add bash build-base openssl-dev util-linux-dev # util-linux-dev contains uuid/uuid.h
    - cd src
    - make test

trigger:
  event:
    - pull_request
    - push